### ISSUE TITLE
status

### ISSUE THREAD

**Issue by ddavidebor** [DOKOS-IO/mautic_integration#1]
Hi, 

is this working? What features does it have?

David

**Comment by chdecultot** [comment]
Hi @ddavidebor,

This is a prototype under actual development.

**Currently it does the following:**

- Pull all contacts from Mautic to ERPNext
- Pull all organizations from Mautic to ERPNext
- Pull the organization address from Mautic to ERPNext

**We are working on the following:**

- Pull organizations to Suppliers in ERPNext based on a variable search criteria
- Pull contacts or customers to leads in ERPNext based on a variable search criteria
- Push contacts, leads and customers from ERPNext to Mautic based on criteria available within ERPNext
- Enhance the connection user experience (currently the connection success is a blank page with an empty bracket in the top left) ;-)
- Create a documentation

If you have any suggestion, please don't hesitate!
